// reduce the large history.xml to arcade only version
// for easier retrieval of informations 53 megs => 14 megs
const { XMLParser, XMLBuilder } = require("fast-xml-parser");
const fs = require("fs");
const { parserOptions, builderOptions } = require("./options");

const XMLdata = fs.readFileSync("./history.xml");

const parser = new XMLParser(parserOptions);

let jObj = parser.parse(XMLdata);

const arcadeOnly = jObj.history.entry.filter((entry) => !!entry.systems);

const systemsMap = {};
arcadeOnly.forEach((item) => {
    const text = item.text;
    const systems = Array.isArray(item.systems.system) ? item.systems.system : [item.systems.system];
    systems.forEach((system) => {
        systemsMap[system['@_name']] = text;
    })
})

const data = `// this file is auto generated by arcade-only.js and history.xml
// you can get history.xml here https://www.arcade-history.com/index.php?page=download
module.exports = {
    arcadeDescriptions: ${JSON.stringify(systemsMap, null, 2)}
}
`;

fs.writeFileSync('arcade-descriptions.js', data, { enconding: 'utf-8' });